# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('buyer_uuid', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('seller_uuid', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('price', models.FloatField()),
                ('state', models.CharField(choices=[(b'Awaiting seller confirmation', b'Awating seller confirmation'), (b'Awaiting payment', b'Awaiting payment'), (b'Awaiting shipping', b'Awaiting shipping'), (b'Shipped', b'Shipped'), (b'Refund', b'Refund'), (b'Completed', b'Completed')], db_index=True, default=b'Awaiting seller confirmation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.Object')),
            ],
        ),
    ]
