# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('to_uuid', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('from_uuid', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('price', models.FloatField()),
                ('state', models.CharField(choices=[(b'AWAITING_CONFIRMATION', b'Awaiting confirmation'), (b'AWAITING_PAYMENT', b'Awaiting payment'), (b'AWAITING_SHIPPING', b'Awaiting shipping'), (b'SHIPPED', b'Shipped'), (b'REFUND', b'Refund'), (b'COMPLETED', b'Completed')], db_index=True, default=b'Awaiting confirmation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.Object')),
            ],
        ),
    ]
