# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='from_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='to_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
    ]
