# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20161015_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='tracking_code',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
